#!/usr/bin/env Rscript

# install/update commonly used R packages from CRAN
pkgs_cran <- c(
  "anesrake",
  "anytime",
  "archive",
  "arrow",
  "asciicast",
  "assertr",
  "available",
  "bench",
  "BFS",
  "blastula",
  "blogdown",
  "bookdown",
  "brio",
  "broom",
  "checkmate",
  "cli",
  "clipr",
  "clock",
  "commonmark",
  "constructive",
  "covr",
  "crayon",
  "crosstalk",
  "crul",
  "curl",
  "daff",
  "datapasta",
  "DBI",
  "deeplr",
  "desc",
  "DescTools",
  "devtools",
  "DiagrammeR",
  "DiagrammeRsvg",
  "dials",
  "diffobj",
  "diffviewer",
  "digest",
  "dm",
  "dplyr",
  "dqrng",
  "DT",
  "duckdb",
  "forcats",
  "fs",
  "gargle",
  "gert", # needs to be installed from source to resolve the "failed to start SSH session: Unable to ask for ssh-userauth service" error
  "ggeffects",
  "ggforce",
  "ggiraph",
  "ggplot2",
  "ggstream",
  "gh",
  "gitlabr",
  "glue",
  "googledrive",
  "googlesheets4",
  "graphql",
  "gt",
  "gtsummary",
  "haven",
  "heck",
  "hexSticker",
  "hms",
  "htmltools",
  "htmlwidgets",
  "httr2",
  "imager",
  "infer",
  "ISOcodes",
  "janitor",
  "jsonlite",
  "kableExtra",
  "katex",
  "keyring",
  "knitr",
  "komaletter",
  "labelled",
  "languageserver",
  "learnr",
  "lifecycle",
  "lintr",
  "listviewer",
  "lobstr",
  "lubridate",
  "magick",
  "magrittr",
  "miniUI",
  "mirt",
  "modeldata",
  "modelr",
  "mongolite",
  "oai",
  "openssl",
  "pak",
  "paletteer",
  "pander",
  "parsedate",
  "parsnip",
  "pins",
  "pkgbuild",
  "pkgcache",
  "pkgdepends",
  "pkgdown",
  "pkgload",
  "pkgsearch",
  "plotly",
  "plumber",
  "prettycode",
  "prettyunits",
  "purrr",
  "qpdf",
  "qs",
  "quarto",
  "R6",
  "ragg",
  "rcmdcheck",
  "RColorBrewer",
  "Rcpp",
  "RcppTOML",
  "RCurl",
  "readODS",
  "readr",
  "readxl",
  "recipes",
  "remotes",
  "renv",
  "reprex",
  "reticulate",
  "revealjs",
  "rex",
  "rio",
  "rJava",
  "rlang",
  "rmarkdown",
  "roxygen2",
  "RPostgres",
  "rprojroot",
  "rsample",
  "rsconnect",
  "RSelenium",
  "rstudioapi",
  "rsvg",
  "rvest",
  "s2",
  "s3fs",
  "servr",
  "sessioninfo",
  "sf",
  "shiny",
  "showtext",
  "skimr",
  "staplr",
  "stringdist",
  "stringi",
  "stringr",
  "styler",
  "swissparl",
  "testthat",
  "tibble",
  "tidyr",
  "tidyRSS",
  "tidyselect",
  "tidytext",
  "tidyverse",
  "tiff",
  "tinkr",
  "tokenizers",
  "tune",
  "tweenr",
  "uaparserjs",
  "units",
  "urltools",
  "usethis",
  "uuid",
  "V8",
  "vctrs",
  "viridis",
  "visdat",
  "vroom",
  "webshot2",
  "whoami",
  "widyr",
  "withr",
  "workflows",
  "writexl",
  "xfun",
  "xml2",
  "xopen",
  "xslt",
  "yaml",
  "yardstick",
  "yesno",
  "zip"
)

## install pkgs the first time
pkgs_cran |>
  setdiff(y = installed.packages()[, "Package"]) |>
  install.packages(dependencies = TRUE)

## update pkgs (fails if run with `dependencies = TRUE`)
pak::pkg_install(pkg = pkgs_cran,
                 ask = FALSE,
                 dependencies = FALSE)

# install/update packages not (yet/anymore) on CRAN directly from Git forges
## third-party packages
pak::pkg_install(pkg = c("github::mattflor/chorddiag",
                         "github::konradedgar/extraInserts",
                         "github::nx10/httpgd",
                         "github::hrbrmstr/qrencoder",
                         "github::LudvigOlsen/splitChunk",
                         "github::politanch/swissdd",
                         "github::ManuelHentschel/vscDebugger"),
                 ask = FALSE,
                 dependencies = TRUE)
## own packages
### TODO: use `pak::pkg_install()` once https://github.com/r-lib/pak/issues/796 is resolved
remotes::install_gitlab(repo = "salim_b/r/pkgs/salim",
                        dependencies = TRUE,
                        upgrade = FALSE)
salim::update_rpkgs()
salim::update_salims_pkgs()
salim::update_zdaarau_pkgs(pkgs = c("rdb.report", "fokus", "swissevote"))
remotes::install_gitlab(repo = "zdaarau/rpkgs/rdb@pg",
                        dependencies = TRUE,
                        upgrade = FALSE)

## third-party pkgs with notable (own) unmerged PRs for which we maintain an "interim" branch
pak::pkg_install(pkg = c("github::salim-b/lintr", # TODO: remove once lintr 3.2.1+ is released
                         "github::salim-b/plotly.R@interim-merge",
                         "github::salim-b/quarto-r", # TODO: remove once quarto 1.4.5+ is released
                         "github::salim-b/roxygen2@interim-merge",
                         "github::salim-b/rprojroot@interim-merge",
                         "github::salim-b/rscodeio@interim-merge"),
                 ask = FALSE)
