name: build-boxkit
on:
  workflow_dispatch: # allow manually triggering builds
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
      - '!.editorconfig'
      - '!.github/**'
      - '.github/workflows/build-boxkit.yml'
      - '!LICENSE'
      - '!renovate.json'
  schedule:
    - cron: '0 0 * * TUE'

env:
    IMAGE_TAGS: latest
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    IMAGE_CACHE_REPOSITORY: buildah-cache

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        containerfile:
          - ubuntu-toolbox-salim
    steps:
      # Remove unused stuff to free disk space on runner
      - name: Free disk space
        uses: endersonmenezes/free-disk-space@2a22f8c59cae9cddae7194b33e6b92d023b2b4b8 # v4.0.0
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: false
          remove_swap: true
          # enable to free another ~5 GiB for the price of another ~90s delay
          # remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell /usr/local/julia /usr/local/aws-cli /usr/local/aws-sam-cli /usr/share/gradle"
          rm_cmd: "rmz"  # see https://github.com/SUPERCILEX/fuc for more info
          rmz_version: "3.1.1"
          testing: false

      # Clone code to runner
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Build metadata
      - name: Prepare metadata
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: meta
        with:
          images: |
            ${{ matrix.containerfile }}
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/salim-b/boxkit/main/README.md

      # Build image using Buildah
      - name: Create secrets file
        run: echo "${{ secrets.GITHUB_TOKEN }}" > /tmp/github_token.txt

      - name: Log in to GHCR
        if: github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set Buildah `extra-args`
        id: buildah_args
        shell: bash
        run: |
          {
            echo 'extra_args<<EOF'
            echo '--secret=id=GITHUB_TOKEN,src=/tmp/github_token.txt'
            echo '--cache-from=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_CACHE_REPOSITORY }}'
            if [[ "${{ github.event_name }}" != "pull_request" || "${{ github.event.pull_request.head.repo.fork }}" != "true" ]]; then
              echo '--cache-to=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_CACHE_REPOSITORY }}'
            fi
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@3a51aade9afa17e5c78256bcbe2e1ee08c7b995b # v3.0.2
        with:
          containerfiles: |
            ./ContainerFiles/${{ matrix.containerfile }}
          image: ${{ matrix.containerfile }}
          tags: ${{ env.IMAGE_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: true
          layers: true
          build-args: |
            CACHEBUST=${{ github.run_id }}
          extra-args: ${{ steps.buildah_args.outputs.extra_args }}

      # Push image to GHCR
      # TODO: Submit PR to `redhat-actions/push-to-registry` to do this
      - name: Enable Sigstore attachments
        run: |
          sudo mkdir -p /etc/containers/registries.d
          cat <<EOF | sudo tee /etc/containers/registries.d/default.yaml
          default-docker:
            use-sigstore-attachments: true
          EOF

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
        if: github.event_name != 'pull_request'
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          sigstore-private-key: ${{ secrets.SIGNING_SECRET }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
